#alphabetical order
#angry
image angry_00 = "images/eliana/angry_00.png"
image angry_01 = "images/eliana/angry_01.png"
image angry_02 = "images/eliana/angry_02.png"
image angry_03 = "images/eliana/angry_03.png"
#angry idle animations
image angry_idle_00 = "images/eliana/angry_idle_00.png"
image angry_idle_01 = "images/eliana/angry_idle_01.png"
image angry_idle_02 = "images/eliana/angry_idle_02.png"
image angry_idle_03 = "images/eliana/angry_idle_03.png"
image angry_idle_04 = "images/eliana/angry_idle_04.png"
#angry idle animations (blinks)
image angry_idle_blink_00 = "images/eliana/angry_idle_blink_00.png"
image angry_idle_blink_01 = "images/eliana/angry_idle_blink_01.png"
image angry_idle_blink_02 = "images/eliana/angry_idle_blink_02.png"
image angry_idle_blink_03 = "images/eliana/angry_idle_blink_03.png"
image angry_idle_blink_04 = "images/eliana/angry_idle_blink_04.png"
#embarrassed
image embarrassed_00 = "images/eliana/embarrassed_00.png"
image embarrassed_01 = "images/eliana/embarrassed_01.png"
image embarrassed_02 = "images/eliana/embarrassed_02.png"
image embarrassed_03 = "images/eliana/embarrassed_03.png"
image embarrassed_04 = "images/eliana/embarrassed_04.png"
#evil
image evil_00 = "images/eliana/evil_00.png"
image evil_01 = "images/eliana/evil_01.png"
image evil_02 = "images/eliana/evil_02.png"
image evil_03 = "images/eliana/evil_03.png"
#high affection idle animations
image high_aff_idle_00 = "images/eliana/high_aff_idle_00.png"
image high_aff_idle_01 = "images/eliana/high_aff_idle_01.png"
image high_aff_idle_02 = "images/eliana/high_aff_idle_02.png"
image high_aff_idle_03 = "images/eliana/high_aff_idle_03.png"
image high_aff_idle_04 = "images/eliana/high_aff_idle_04.png"
#high affection idle animations (blinks)
image high_aff_idle_blink_00 = "images/eliana/high_aff_idle_blink_00.png"
image high_aff_idle_blink_01 = "images/eliana/high_aff_idle_blink_01.png"
image high_aff_idle_blink_02 = "images/eliana/high_aff_idle_blink_02.png"
image high_aff_idle_blink_03 = "images/eliana/high_aff_idle_blink_03.png"
image high_aff_idle_blink_04 = "images/eliana/high_aff_idle_blink_04.png"
#default affection idle animations
image idle_00 = "images/eliana/idle_00.png"
image idle_01 = "images/eliana/idle_01.png"
image idle_02 = "images/eliana/idle_02.png"
image idle_03 = "images/eliana/idle_03.png"
image idle_04 = "images/eliana/idle_04.png"
#default affection idle animations (blinks)
image idle_blink_00 = "images/eliana/idle_blink_00.png"
image idle_blink_01 = "images/eliana/idle_blink_01.png"
image idle_blink_02 = "images/eliana/idle_blink_02.png"
image idle_blink_03 = "images/eliana/idle_blink_03.png"
image idle_blink_04 = "images/eliana/idle_blink_04.png"
#joyful
image joyful_00 = "images/eliana/joyful_00.png"
image joyful_01 = "images/eliana/joyful_01.png"
image joyful_02 = "images/eliana/joyful_02.png"
image joyful_03 = "images/eliana/joyful_03.png"
image joyful_04 = "images/eliana/joyful_04.png"
image joyful_05 = "images/eliana/joyful_05.png"
image joyful_06 = "images/eliana/joyful_06.png"
image joyful_07 = "images/eliana/joyful_07.png"
#laughs
image laugh_00 = "images/eliana/laugh_00.png"
image laugh_01 = "images/eliana/laugh_01.png"
image laugh_02 = "images/eliana/laugh_02.png"
image laugh_03 = "images/eliana/laugh_03.png"
image laugh_04 = "images/eliana/laugh_04.png"
#low affection idle animations
image low_aff_idle_00 = "images/eliana/low_aff_idle_00.png"
image low_aff_idle_01 = "images/eliana/low_aff_idle_01.png"
image low_aff_idle_02 = "images/eliana/low_aff_idle_02.png"
image low_aff_idle_03 = "images/eliana/low_aff_idle_03.png"
image low_aff_idle_04 = "images/eliana/low_aff_idle_04.png"
#low affection idle animations (blinks)
image low_aff_idle_blink_00 = "images/eliana/low_aff_idle_blink_00.png"
image low_aff_idle_blink_01 = "images/eliana/low_aff_idle_blink_01.png"
image low_aff_idle_blink_02 = "images/eliana/low_aff_idle_blink_02.png"
image low_aff_idle_blink_03 = "images/eliana/low_aff_idle_blink_03.png"
image low_aff_idle_blink_04 = "images/eliana/low_aff_idle_blink_04.png"
#neutral
image neutral_00 = "images/eliana/neutral_00.png"
image neutral_01 = "images/eliana/neutral_01.png"
image neutral_02 = "images/eliana/neutral_02.png"
#sinner idle animations
image sinner_idle_00 = "images/eliana/sinner_idle_00.png"
image sinner_idle_01 = "images/eliana/sinner_idle_01.png"
image sinner_idle_02 = "images/eliana/sinner_idle_02.png"
image sinner_idle_03 = "images/eliana/sinner_idle_03.png"
image sinner_idle_04 = "images/eliana/sinner_idle_04.png"
#sinner idle animations (blinks)
image sinner_idle_blink_00 = "images/eliana/sinner_idle_blink_00.png"
image sinner_idle_blink_01 = "images/eliana/sinner_idle_blink_01.png"
image sinner_idle_blink_02 = "images/eliana/sinner_idle_blink_02.png"
image sinner_idle_blink_03 = "images/eliana/sinner_idle_blink_03.png"\
image sinner_idle_blink_04 = "images/eliana/sinner_idle_blink_04.png"
#talking
image talking_00 = "images/eliana/talking_00.png"
image talking_01 = "images/eliana/talking_01.png"
image talking_02 = "images/eliana/talking_02.png"
