#alphabetical order
#angry
image eliana angry_00 = "images/eliana/angry_00.png"
image eliana angry_01 = "images/eliana/angry_01.png"
image eliana angry_02 = "images/eliana/angry_02.png"
image eliana angry_03 = "images/eliana/angry_03.png"
#angry idle animations
image eliana angry_idle_00 = "images/eliana/angry_idle_00.png"
image eliana angry_idle_01 = "images/eliana/angry_idle_01.png"
image eliana angry_idle_02 = "images/eliana/angry_idle_02.png"
image eliana angry_idle_03 = "images/eliana/angry_idle_03.png"
image eliana angry_idle_04 = "images/eliana/angry_idle_04.png"
#angry idle animations (blinks)
image eliana angry_idle_blink_00 = "images/eliana/angry_idle_blink_00.png"
image eliana angry_idle_blink_01 = "images/eliana/angry_idle_blink_01.png"
image eliana angry_idle_blink_02 = "images/eliana/angry_idle_blink_02.png"
image eliana angry_idle_blink_03 = "images/eliana/angry_idle_blink_03.png"
image eliana angry_idle_blink_04 = "images/eliana/angry_idle_blink_04.png"
#annoyed
image eliana annoyed_00 = "images/eliana/annoyed_00.png"
image eliana annoyed_01 = "images/eliana/annoyed_01.png"
#embarrassed
image eliana embarrassed_00 = "images/eliana/embarrassed_00.png"
image eliana embarrassed_01 = "images/eliana/embarrassed_01.png"
image eliana embarrassed_02 = "images/eliana/embarrassed_02.png"
image eliana embarrassed_03 = "images/eliana/embarrassed_03.png"
image eliana embarrassed_04 = "images/eliana/embarrassed_04.png"
#enamored idle animations
image eliana enamored_idle_00 = "images/eliana/enamored_idle_00.png"
image eliana enamored_idle_01 = "images/eliana/enamored_idle_01.png"
image eliana enamored_idle_02 = "images/eliana/enamored_idle_02.png"
image eliana enamored_idle_03 = "images/eliana/enamored_idle_03.png"
image eliana enamored_idle_04 = "images/eliana/enamored_idle_04.png"
#enamored idle animations (blinks)
image eliana enamored_idle_blink_00 = "images/eliana/enamored_idle_blink_00.png"
image eliana enamored_idle_blink_01 = "images/eliana/enamored_idle_blink_01.png"
image eliana enamored_idle_blink_02 = "images/eliana/enamored_idle_blink_02.png"
image eliana enamored_idle_blink_03 = "images/eliana/enamored_idle_blink_03.png"
image eliana enamored_idle_blink_04 = "images/eliana/enamored_idle_blink_04.png"
#evil
image eliana evil_00 = "images/eliana/evil_00.png"
image eliana evil_01 = "images/eliana/evil_01.png"
image eliana evil_02 = "images/eliana/evil_02.png"
image eliana evil_03 = "images/eliana/evil_03.png"
#high affection idle animations
image eliana high_aff_idle_00 = "images/eliana/high_aff_idle_00.png"
image eliana high_aff_idle_01 = "images/eliana/high_aff_idle_01.png"
image eliana high_aff_idle_02 = "images/eliana/high_aff_idle_02.png"
image eliana high_aff_idle_03 = "images/eliana/high_aff_idle_03.png"
image eliana high_aff_idle_04 = "images/eliana/high_aff_idle_04.png"
#high affection idle animations (blinks)
image eliana high_aff_idle_blink_00 = "images/eliana/high_aff_idle_blink_00.png"
image eliana high_aff_idle_blink_01 = "images/eliana/high_aff_idle_blink_01.png"
image eliana high_aff_idle_blink_02 = "images/eliana/high_aff_idle_blink_02.png"
image eliana high_aff_idle_blink_03 = "images/eliana/high_aff_idle_blink_03.png"
image eliana high_aff_idle_blink_04 = "images/eliana/high_aff_idle_blink_04.png"
#huh
image eliana huh_00 = "images/eliana/huh_00.png"
image eliana huh_01 = "images/eliana/huh_01.png"
image eliana huh_02 = "images/eliana/huh_02.png"
image eliana huh_03 = "images/eliana/huh_03.png"
#default affection idle animations
image eliana idle_00 = "images/eliana/idle_00.png"
image eliana idle_01 = "images/eliana/idle_01.png"
image eliana idle_02 = "images/eliana/idle_02.png"
image eliana idle_03 = "images/eliana/idle_03.png"
image eliana idle_04 = "images/eliana/idle_04.png"
#default affection idle animations (blinks)
image eliana idle_blink_00 = "images/eliana/idle_blink_00.png"
image eliana idle_blink_01 = "images/eliana/idle_blink_01.png"
image eliana idle_blink_02 = "images/eliana/idle_blink_02.png"
image eliana idle_blink_03 = "images/eliana/idle_blink_03.png"
image eliana idle_blink_04 = "images/eliana/idle_blink_04.png"
#joyful
image eliana joyful_00 = "images/eliana/joyful_00.png"
image eliana joyful_01 = "images/eliana/joyful_01.png"
image eliana joyful_02 = "images/eliana/joyful_02.png"
image eliana joyful_03 = "images/eliana/joyful_03.png"
image eliana joyful_04 = "images/eliana/joyful_04.png"
image eliana joyful_05 = "images/eliana/joyful_05.png"
image eliana joyful_06 = "images/eliana/joyful_06.png"
image eliana joyful_07 = "images/eliana/joyful_07.png"
#laughs
image eliana laugh_00 = "images/eliana/laugh_00.png"
image eliana laugh_01 = "images/eliana/laugh_01.png"
image eliana laugh_02 = "images/eliana/laugh_02.png"
image eliana laugh_03 = "images/eliana/laugh_03.png"
image eliana laugh_04 = "images/eliana/laugh_04.png"
#low affection idle animations
image eliana low_aff_idle_00 = "images/eliana/low_aff_idle_00.png"
image eliana low_aff_idle_01 = "images/eliana/low_aff_idle_01.png"
image eliana low_aff_idle_02 = "images/eliana/low_aff_idle_02.png"
image eliana low_aff_idle_03 = "images/eliana/low_aff_idle_03.png"
image eliana low_aff_idle_04 = "images/eliana/low_aff_idle_04.png"
#low affection idle animations (blinks)
image eliana low_aff_idle_blink_00 = "images/eliana/low_aff_idle_blink_00.png"
image eliana low_aff_idle_blink_01 = "images/eliana/low_aff_idle_blink_01.png"
image eliana low_aff_idle_blink_02 = "images/eliana/low_aff_idle_blink_02.png"
image eliana low_aff_idle_blink_03 = "images/eliana/low_aff_idle_blink_03.png"
image eliana low_aff_idle_blink_04 = "images/eliana/low_aff_idle_blink_04.png"
#neutral
image eliana neutral_00 = "images/eliana/neutral_00.png"
image eliana neutral_01 = "images/eliana/neutral_01.png"
image eliana neutral_02 = "images/eliana/neutral_02.png"
#sinner idle animations
image eliana sinner_idle_00 = "images/eliana/sinner_idle_00.png"
image eliana sinner_idle_01 = "images/eliana/sinner_idle_01.png"
image eliana sinner_idle_02 = "images/eliana/sinner_idle_02.png"
image eliana sinner_idle_03 = "images/eliana/sinner_idle_03.png"
image eliana sinner_idle_04 = "images/eliana/sinner_idle_04.png"
#sinner idle animations (blinks)
image eliana sinner_idle_blink_00 = "images/eliana/sinner_idle_blink_00.png"
image eliana sinner_idle_blink_01 = "images/eliana/sinner_idle_blink_01.png"
image eliana sinner_idle_blink_02 = "images/eliana/sinner_idle_blink_02.png"
image eliana sinner_idle_blink_03 = "images/eliana/sinner_idle_blink_03.png"
image eliana sinner_idle_blink_04 = "images/eliana/sinner_idle_blink_04.png"
#talking
image eliana talking_00 = "images/eliana/talking_00.png"
image eliana talking_01 = "images/eliana/talking_01.png"
image eliana talking_02 = "images/eliana/talking_02.png"
#terrified
image eliana terrified_00 = "images/eliana/terrified_00.png"
image eliana terrified_01 = "images/eliana/terrified_01.png"
image eliana terrified_02 = "images/eliana/terrified_02.png"
image eliana terrified_03 = "images/eliana/terrified_03.png"
image eliana terrified_04 = "images/eliana/terrified_04.png"
#tsun
image eliana tsun_00 = "images/eliana/tsun_00.png"
image eliana tsun_01 = "images/eliana/tsun_01.png"
